import Head from "next/head";
import Image from "next/image";

import Hero from "@/components/functional/Hero";
import Score from "@/components/functional/Score";
import About from "@/components/functional/About";
import AboutUs from "@/components/functional/AboutUs";
import Contact from "@/components/functional/Contact";
import Customers from "@/components/functional/Customers";
import Services from "@/components/functional/Services";
import Holding from "@/components/functional/Holding";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero/>
        <Score/>
        <About/>
        <Services/>
        <AboutUs/>
        <Holding/>
        <Contact/>
        <Customers/>
      </main>
    </>
  );
}
