import Head from "next/head";
import Image from "next/image";

import Hero from "@/components/functional/Hero";
import Score from "@/components/functional/Score";
import About from "@/components/functional/About";
import AboutUs from "@/components/functional/AboutUs";
import Contact from "@/components/functional/Contact";
import Customers from "@/components/functional/Customers";
import Services from "@/components/functional/Services";
import Holding from "@/components/functional/Holding";
import History from "@/components/functional/History";
import Footer from "@/components/functional/Footer";

import Wallpaper from "@/components/ui/Wallpaper";
import withScrollAnimation from "@/components/ui/Framer";
import {
  TitleBackground,
  TitleBackgroundAbsolute,
} from "@/components/ui/TitleBackground";
import { motion } from "framer-motion";

export default function Home() {
  const AnimateDiv = withScrollAnimation("div");
  return (
    <>
      <Head>
        <title>Serviclick - Todas las soluciones en la palma de tu mano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/hero/logocolor.png" />
      </Head>
      <main>
        <Hero />
        <AnimateDiv>
          <Score
            content={[
              {
                unitTextLeft: "+",
                title: 21,
                text: "Años de Experiencia",
                duration: 150,
              },
              {
                unitTextLeft: "+",
                title: 899,
                unitTextRight: "M",
                text: "Clientes Finales ",
                duration: 0.45,
              },
              {
                unitTextLeft: "+",
                title: 19,
                text: "Alianzas y Clientes",
                duration: 150,
              },
              {
                title: 23,
                unitTextRight: "hrs",
                text: "Presentes en todo Chile ",
                duration: 130,
              },
            ]}
          />
        </AnimateDiv>

        <Wallpaper img="/img/score/FondoAbout.png" width="1288" height="850">
          <About />
          <Services />
        </Wallpaper>
        <Wallpaper img="/img/aboutus/fondo.png" width="1288px" height="519px">
          <AboutUs />
        </Wallpaper>
        <TitleBackgroundAbsolute
          title="Serviclick es parte de MHM Empresas"
          backgroundColor="white"
          color="#03495C"
          fontSize=""
        />
        <Holding />
        <Customers />
        <Wallpaper img="/img/history/fondo.png" width="1297px" height="1440px">
          <History />
        </Wallpaper>
        <Contact img="/img/contact/mapa.png" width="280px" height="240px" />
        <Footer />
      </main>
    </>
  );
}
