import React from "react";
import Head from "next/head";

import Layout from "@/components/Layout/Layout";

import Title from "@/components/ui/Title";

import styles from "../components/Layout/Layout.module.scss";
import Cards from "@/components/ui/Cards";

export default function servicios() {
  return (
    <>
      <Layout>
        <Head>
          <title>Servicios</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=2" />
          <link rel="icon" href="/img/hero/logocolor.png" />
        </Head>
        <main className={styles.layout}>
          <div className={styles.title}>
            <div className={styles.line}></div>
            <Title
              title="Encuentra nuestros servicios aquí"
              color="#03495C"
              size="large"
            />
          </div>

          <div className={styles.cards}>
            <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
             <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
             <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
             <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
            <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
            <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
            <Cards
              img="/img/layout/img.png"
              title="BCI Sala de urgencia"
              description="Podrás obtener benecios en: texto texto textotexto texto texto texto texto textotexto texto texto texto texto "
              button="Conoce más "
            />
          </div>
        </main>
      </Layout>
    </>
  );
}
